This is about Python-Exception.
